# Generated by Django 5.0.1 on 2024-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
